version: "2"

services:
    wordpress:
        image: wordpress
        ports:
            - "8000:80"
        environment:
            - WORDPRESS_DB_PASSWORD=exmaple
        volumes:
            - ./wordpress-data:/var/www/html
        container_name: wordpress

    mysql:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: exmaple
        volumes:
            - ./mysql-data:/var/lib/mysql
