version: '3.1' # if no version is specified then v1 is assumed. Recommend v2 minimum

services: # containers, same as docker run
  servicename: # friendly name, this is also DNS name inside the network
    image: # Optional, if you use build
    command: # Optional, replace the default CMD specified by the image
    environment: # Optional, adds environment variables to docker run command
    volumes: # Optional, specifies volumes that the container can connect to
  servicename2:

volumes: # Optional, same as docker volume create

networks: # Optional, same as docker network create